name: Build & Push to ECR
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1
    - uses: aws-actions/amazon-ecr-login@v1
    - uses: docker/build-push-action@v6
      with:
        context: ./app
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ github.sha }}
          ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:latest